### PR TITLE
Make import of `SqlBackend` fields explicit

### PR DESCRIPTION
**Pull request by mjgpy3**
Per this stackage issue: https://github.com/commercialhaskell/stackage/issues/6032

### CODE REVIEW

**Review by z0isch — APPROVED** [review]
Hmm- I guess `Database.Persist.Sql` stopped exporting these fields? I wonder why?

**Comment by mjgpy3** [comment]
@z0isch good question! Seems to have happened in this PR: https://github.com/yesodweb/persistent/pull/1225

Maybe this is indicating that we're not building this totally correctly...

**Comment by mjgpy3** [comment]
I'll dig in a little more before merging this.

**Comment by z0isch** [comment]
> @z0isch good question! Seems to have happened in this PR: [yesodweb/persistent#1225](https://github.com/yesodweb/persistent/pull/1225)
> 
> Maybe this is indicating that we're not building this totally correctly...

Yeah it looks like we should maybe switch to the [mkSqlBackend](https://www.stackage.org/haddock/nightly-2021-05-23/persistent-2.13.0.1/Database-Persist-SqlBackend-Internal.html#v:mkSqlBackend) function?

**Comment by pbrisbin** [comment]
Just a headsup that getting green CI doesn't always indicate you've fixed something like this. In most projects, we run CI with the latest LTS resolver. Sometimes we also build with older resolvers. We rarely have a CI job with `nightly` and we *never* build with latest Hackage.

That means that if we have a lax upper bound (which we're moving to) we could see breakage with a newer nightly/hackage dependency that won't reproduce on CI.

I'm stilling thinking of the best way to address that fact, for now it's kind of just a "be advised" situation like this. Making a nightly CI job part of our prescribed suites could be good enough (latest Hackage feels like overkill).

**Comment by mjgpy3** [comment]
@z0isch I think that that constructor function may not be too great here. Since our pattern to _modify_ an existing backend creating a new one feels tedious and requires me to use those internal fields anyways (to map all existing, required fields that we don't modify over -- looks like 10 fields).

@pbrisbin I tried constraining my local build to take a fresher persistent (`persistent >= 2.13.0.0`) and this built. Does that serve as an adequate test?

**Comment by pbrisbin** [comment]
@mjgpy3 I'd imagine that works. I would've probably just built with `--resolver nightly` since that's quicker and should reproduce what the Stackage curators hit.

**Pull request merged**
